name: test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: debian:trixie-20250113-slim
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: docker build --no-cache --progress=plain .
